version: '3'

services:
  php:
      container_name: laravel_docker_php
      build: ./php
      volumes:
        - ./www/api:/www/api
      working_dir: /www/api
  nginx:
    image: nginx
    container_name: laravel_docker_nginx
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./www/api:/www/api
    ports:
      - 80:80
    links:
      - php
    depends_on:
      - php
  mysql:
    build: ./mysql
    container_name: laravel_docker_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_docker_db
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql_data:/var/lib/mysql
    ports:
    - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_docker_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 1234:80
    volumes:
      - /sessions

  # mailhog:
  #     image: mailhog/mailhog
  #     container_name: laravel_docker_mailhog
  #     ports:
  #        - "1025:1025"
  #        - "8025:8025"
